### ISSUE TITLE
Trying to use etcd in omnimode

### ISSUE THREAD

**Issue by delianides** [progrium/ambassadord#14]
Im setting up fleet services in CoreOS. I'm using registrator + ambassadord to set up service discovery across multiple hosts.

From what I can tell I'm stuck trying to get a container to recognize whats in etcd. 

**Starting Registrator**
`docker run --rm --name registrator -v /var/run/docker.sock:/tmp/docker.sock progrium/registrator -ip=${COREOS_PRIVATE_IPV4} etcd://${COREOS_PRIVATE_IPV4}:4001/services`

**Starting Ambassadord**
`docker run --rm --name backends -v /var/run/docker.sock:/var/run/docker.sock progrium/ambassadord --omnimode`

**Starting Redis**
`docker run --name redis -p 6379:6379 -e SERVICE_NAME=redis dockerfile/redis`

**etcd status after registrator**
`$ etcdctl get /services/redis/core-01:redis:6379`
`$ 172.17.8.102:6739 `

**Trying to PING the Redis container on a different host**
`docker run -it --rm --link backends:redis -e BACKEND_6379="etcd://${COREOS_PRIVATE_IPV4}/services/redis" dockerfile/redis bash -c 'redis-cli ping'`

**Result**
`Could not connect to Redis at 127.0.0.1:6379: Connection refused`

The last docker run errors because its trying to connect to redis on localhost. Am I missing something? Do I have to build a container that supports ambassadord?

**Comment by stuart-warren** [comment]
I get the same thing

**Comment by progrium** [comment]
Sorry, the Redis client container is not going to get the backend on
localhost (as redis-cli will assume, hence 127.0.0.1 in error). Instead you
have to specify the host of "redis" which is the name of the link you
created to "backends". Does that make sense? This might change soon
hopefully to simplify.

On Wed, Jan 14, 2015 at 5:30 PM, Woz <notifications@github.com> wrote:

> I get the same thing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/ambassadord/issues/14#issuecomment-70014050>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by stuart-warren** [comment]
Doesn't seem to make a difference:
```
$ docker run -it --rm --link backends:redis -e BACKEND_6379="etcd://${COREOS_PRIVATE_IPV4}/services/redis" dockerfile/redis bash -c 'redis-cli -h redis ping'
Could not connect to Redis at redis:6379: Connection refused
```

I noticed that @delianides hadn't run:
```
$ docker run --rm --privileged --net container:backends progrium/ambassadord --setup-iptables
```

But after that I get:
```
$ docker run -it --rm --link backends:redis -e BACKEND_6379="etcd://${COREOS_PRIVATE_IPV4}/services/redis" dockerfile/redis bash -c 'redis-cli -h redis ping'
Error: Connection reset by peer
```
It sort of seems to connect interactively, but that might just be a redis-cli thing:
```
$ docker run -it --rm --link backends:redis -e BACKEND_6379="etcd://${COREOS_PRIVATE_IPV4}/services/redis" dockerfile/redis bash -c 'redis-cli -h redis'
redis:6379> ping
Error: Connection reset by peer
redis:6379>
```
I'm also running on CoreOS, personally within Vagrant, should that be an issue.

**Comment by delianides** [comment]
@progrium Actually that did work. I guess I'm still confused as to why it works. How is the container aware of the `redis` hostname? 

@stuart-warren I did run the --setup-iptables inside the fleet service as a `ExecStartPost`. Example [here](https://github.com/virtuald/coreos-vagrant-ambassadord/blob/master/user-data.sample#L85).

**Comment by stuart-warren** [comment]
@delianides the ``--link backends:redis`` adds an entry to the /etc/hosts file pointing 'redis' to the ip of 'backends'
https://docs.docker.com/userguide/dockerlinks/#updating-the-etchosts-file

**Comment by delianides** [comment]
Ok I see it now. And I also see why you use `--link backends:backends` rather than 'backends:redis' in the example. If you need more than once service linked into a container it makes more sense to name it "backends" then a specific service.

**Comment by delianides** [comment]
@stuart-warren make sure you are running `source /etc/environment` before you run your docker command. Otherwise the `${COREOS_PRIVATE_IPV4}` global won't be set.

**Comment by stuart-warren** [comment]
Yeah, I sourced the environment already thanks

**Comment by delianides** [comment]
@progrium closing this
